// Generated by programmers-tracker from the judge's own examples — do not edit; it is
// replaced after every run. Compile and run with (Solution.kt beside it):
//   kotlinc Solution.kt runner_test.kt -include-runtime -d runner_test.jar && java -cp runner_test.jar RunnerTest

// The user's top-level main is reachable only from package scope — inside the object an
// unqualified main(...) call would resolve to the harness's own entry.
internal fun runnerInvokeSolutionMain() = main(emptyArray())

object RunnerTest {
    private var failures = 0

    @JvmStatic
    fun main(args: Array<String>) {
        check(1, "HelloWorld!", "HelloWorld!")
        println(if (failures == 0) "ALL PASS" else failures.toString() + " FAILED")
        if (failures > 0) kotlin.system.exitProcess(1)
    }

    private fun check(index: Int, stdinText: String, expected: String) {
        val originalIn = System.`in`
        val originalOut = System.out
        val captured = java.io.ByteArrayOutputStream()
        try {
            System.setIn(java.io.ByteArrayInputStream(stdinText.toByteArray()))
            System.setOut(java.io.PrintStream(captured, true))
            runnerInvokeSolutionMain()
        } finally {
            System.setOut(originalOut)
            System.setIn(originalIn)
        }
        // Two normalisations, and only these two: trailing newlines and CRLF to LF.
        val actual = captured.toString().replace("\r\n", "\n").trimEnd('\n')
        val want = expected.replace("\r\n", "\n").trimEnd('\n')
        val ok = actual == want
        println("example " + index + (if (ok) "  PASS" else "  FAIL — expected <" + want + ">, got <" + actual + ">"))
        if (!ok) failures += 1
    }
}
