// Generated by programmers-tracker from the judge's own examples — do not edit; it is
// replaced after every run. Run it with:  node runner_test.js  (Solution.js beside it)
"use strict";
const { spawnSync } = require("child_process");
const path = require("path");

let failures = 0;

function check(index, stdinText, expected) {
    const result = spawnSync(process.execPath, [path.join(__dirname, "Solution.js")], {
        input: stdinText,
        encoding: "utf8",
    });
    // Two normalisations, and only these two: trailing newlines and \r\n to \n.
    const actual = String(result.stdout || "").replace(/\r\n/g, "\n").replace(/\n+$/, "");
    const want = expected.replace(/\r\n/g, "\n").replace(/\n+$/, "");
    // A crash after the right output is still a crash: the judge sees exitCode on the
    // run/testcase frame (protocol §7.1), so a runner that read only stdout passed a
    // solution that printed the answer and then died (#98).
    if (result.status !== 0 || result.error) {
        const detail = String(result.stderr || "").trim().split("\n").pop() || String(result.error || "no stderr");
        console.log("example " + index + "  FAIL — exited " + result.status + ": " + detail);
        failures += 1;
        return;
    }
    const ok = actual === want;
    console.log("example " + index + (ok ? "  PASS" : "  FAIL — expected <" + want + ">, got <" + actual + ">"));
    if (!ok) failures += 1;
}

check(1, "HelloWorld!", "HelloWorld!");
console.log(failures === 0 ? "ALL PASS" : failures + " FAILED");
if (failures > 0) process.exit(1);
