// Generated by programmers-tracker from the judge's own examples — do not edit; it is
// replaced after every run. Run it with:  java RunnerTest.java  (Solution.java beside it)
public class RunnerTest {
    public static void main(String[] args) throws Exception {
        check(1, "HelloWorld!", "HelloWorld!");
        System.out.println(failures == 0 ? "ALL PASS" : failures + " FAILED");
        if (failures > 0) System.exit(1);
    }

    static int failures = 0;

    static void check(int index, String stdin, String expected) throws Exception {
        java.io.InputStream originalIn = System.in;
        java.io.PrintStream originalOut = System.out;
        java.io.ByteArrayOutputStream captured = new java.io.ByteArrayOutputStream();
        try {
            System.setIn(new java.io.ByteArrayInputStream(stdin.getBytes()));
            System.setOut(new java.io.PrintStream(captured, true));
            Solution.main(new String[0]);
        } finally {
            System.setIn(originalIn);
            System.setOut(originalOut);
        }
        // Two normalisations, and only these two. Trailing newlines: the judge accepts a
        // println-terminated last line. Line separators: the judge's expected output uses \n,
        // but THIS runner runs on the user's machine, where println emits \r\n on Windows —
        // a platform artifact, not an answer difference. (Caught by CI's windows-latest gate.)
        String actual = captured.toString().replace("\r\n", "\n").replaceAll("\n+$", "");
        String want = expected.replace("\r\n", "\n").replaceAll("\n+$", "");
        boolean ok = actual.equals(want);
        System.out.println("example " + index + (ok ? "  PASS" : "  FAIL — expected <" + want + ">, got <" + actual + ">"));
        if (!ok) failures++;
    }
}
