// Generated by programmers-tracker from the judge's own examples — do not edit; it is
// replaced after every run. Run with (Solution.cs and runner_test.csproj beside it):
//   dotnet run --project runner_test.csproj
using System;
using System.IO;

public static class RunnerTest
{
    private static int failures = 0;

    public static void Main()
    {
        Check(1, "HelloWorld!", "HelloWorld!");
        Console.WriteLine(failures == 0 ? "ALL PASS" : failures + " FAILED");
        if (failures > 0) Environment.Exit(1);
    }

    private static void Check(int index, string stdinText, string expected)
    {
        TextReader originalIn = Console.In;
        TextWriter originalOut = Console.Out;
        var captured = new StringWriter();
        try
        {
            Console.SetIn(new StringReader(stdinText));
            Console.SetOut(captured);
            Example.Main();
        }
        finally
        {
            Console.SetOut(originalOut);
            Console.SetIn(originalIn);
        }
        // Two normalisations, and only these two: trailing newlines and CRLF to LF.
        string actual = captured.ToString().Replace("\r\n", "\n").TrimEnd('\n');
        string want = expected.Replace("\r\n", "\n").TrimEnd('\n');
        bool ok = actual == want;
        string detail = "  FAIL — expected <" + want + ">, got <" + actual + ">";
        Console.WriteLine("example " + index + (ok ? "  PASS" : detail));
        if (!ok) failures += 1;
    }
}
