# Generated by programmers-tracker from the judge's own examples — do not edit; it is
# replaced after every run. Run it with:  python3 runner_test.py  (Solution.py beside it)
import subprocess
import sys

failures = 0

def check(index, stdin_text, expected):
    global failures
    result = subprocess.run(
        [sys.executable, "Solution.py"], input=stdin_text, capture_output=True, text=True,
    )
    actual = result.stdout.replace("\r\n", "\n").rstrip("\n")
    want = expected.replace("\r\n", "\n").rstrip("\n")
    # A crash after the right output is still a crash: the judge sees exitCode on the
    # run/testcase frame (protocol §7.1), so a runner that read only stdout passed a
    # solution that printed the answer and then died (#98).
    if result.returncode != 0:
        detail = (result.stderr or "").strip().splitlines()
        print(f"example {index}  FAIL — exited {result.returncode}: " + (detail[-1] if detail else "no stderr"))
        failures += 1
        return
    ok = actual == want
    print(f"example {index}  " + ("PASS" if ok else f"FAIL — expected {want!r}, got {actual!r}"))
    if not ok:
        failures += 1

if __name__ == "__main__":
    check(1, "HelloWorld!", "HelloWorld!")
    print("ALL PASS" if failures == 0 else f"{failures} FAILED")
    if failures:
        raise SystemExit(1)
