// Generated by programmers-tracker from the judge's own examples — do not edit; it is
// replaced after every run. Compile and run with (Solution.cpp beside it):
//   g++ -std=c++17 runner_test.cpp -o runner_test && ./runner_test
#include <iostream>
#include <sstream>
#include <string>

#define main runner_solution_main
#include "Solution.cpp"
#undef main

static int runner_failures = 0;

static std::string runner_normalized(const std::string& text) {
    std::string out;
    for (size_t i = 0; i < text.size(); ++i) {
        if (text[i] == '\r' && i + 1 < text.size() && text[i + 1] == '\n') continue;
        out += text[i];
    }
    while (!out.empty() && out.back() == '\n') out.pop_back();
    return out;
}

static void runner_check(int index, const std::string& stdin_text, const std::string& expected) {
    std::istringstream in(stdin_text);
    std::ostringstream captured;
    std::streambuf* old_in = std::cin.rdbuf(in.rdbuf());
    std::streambuf* old_out = std::cout.rdbuf(captured.rdbuf());
    runner_solution_main();
    std::cout.rdbuf(old_out);
    std::cin.rdbuf(old_in);
    std::cin.clear();
    std::string actual = runner_normalized(captured.str());
    std::string want = runner_normalized(expected);
    bool ok = actual == want;
    std::cout << "example " << index
              << (ok ? std::string("  PASS") : "  FAIL — expected <" + want + ">, got <" + actual + ">")
              << "\n";
    if (!ok) runner_failures++;
}

int main() {
    runner_check(1, "HelloWorld!", "HelloWorld!");
    std::cout << (runner_failures == 0 ? std::string("ALL PASS")
                                        : std::to_string(runner_failures) + " FAILED") << "\n";
    return runner_failures == 0 ? 0 : 1;
}
