// Generated by programmers-tracker from the judge's own examples — do not edit; it is
// replaced after every run. Compile and run with (Solution.c beside it):
//   gcc runner_test.c -o runner_test && ./runner_test
// Progress prints to stderr — stdout belongs to the solution under test.
#include <stddef.h>

#define main runner_solution_main
#include "Solution.c"
#undef main

#include <stdio.h>
#include <string.h>

static int runner_failures = 0;

static void runner_normalize(char* text) {
    char* write = text;
    for (char* read = text; *read != '\0'; read++) {
        if (read[0] == '\r' && read[1] == '\n') {
            continue;
        }
        *write++ = *read;
    }
    *write = '\0';
    size_t length = strlen(text);
    while (length > 0 && text[length - 1] == '\n') {
        text[--length] = '\0';
    }
}

static void runner_check(int index, const char* stdin_text, const char* expected) {
    FILE* staged = fopen("runner_stdin.tmp", "wb");
    if (staged == NULL) {
        fprintf(stderr, "example %d  FAIL — could not stage stdin\n", index);
        runner_failures++;
        return;
    }
    fputs(stdin_text, staged);
    fclose(staged);
    fflush(stdout);
    if (freopen("runner_stdin.tmp", "rb", stdin) == NULL) {
        fprintf(stderr, "example %d  FAIL — could not redirect stdin\n", index);
        runner_failures++;
        return;
    }
    if (freopen("runner_stdout.tmp", "wb", stdout) == NULL) {
        fprintf(stderr, "example %d  FAIL — could not redirect stdout\n", index);
        runner_failures++;
        return;
    }
    runner_solution_main();
    fflush(stdout);
    static char actual[65536];
    FILE* captured = fopen("runner_stdout.tmp", "rb");
    size_t read = captured == NULL ? 0 : fread(actual, 1, sizeof(actual) - 1, captured);
    if (captured != NULL) {
        fclose(captured);
    }
    actual[read] = '\0';
    static char want[65536];
    strncpy(want, expected, sizeof(want) - 1);
    want[sizeof(want) - 1] = '\0';
    runner_normalize(actual);
    runner_normalize(want);
    if (strcmp(actual, want) == 0) {
        fprintf(stderr, "example %d  PASS\n", index);
        return;
    }
    fprintf(stderr, "example %d  FAIL — expected <%s>, got <%s>\n", index, want, actual);
    runner_failures++;
}

int main(void) {
    runner_check(1, "HelloWorld!", "HelloWorld!");
    if (runner_failures == 0) {
        fprintf(stderr, "ALL PASS\n");
    } else {
        fprintf(stderr, "%d FAILED\n", runner_failures);
    }
    remove("runner_stdin.tmp");
    remove("runner_stdout.tmp");
    return runner_failures == 0 ? 0 : 1;
}
