<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>LatestMajor</RollForward>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>runner_test</AssemblyName>
    <StartupObject>RunnerTest</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Solution.cs" />
    <Compile Include="runner_test.cs" />
  </ItemGroup>
</Project>
