// Generated by programmers-tracker from the judge's own examples — do not edit; it is
// replaced after every run. Run it with:  java RunnerTest.java  (Solution.java beside it)
public class RunnerTest {
    public static void main(String[] args) {
        check(1, new Solution().solution(2, 3), -1);
        check(2, new Solution().solution(100, 2), 98);
        System.out.println(failures == 0 ? "ALL PASS" : failures + " FAILED");
        if (failures > 0) System.exit(1);
    }

    static int failures = 0;

    // deepEquals alone: it already compares arrays deeply and every boxed scalar, so a
    // rendered-string comparison beside it could only ever ADD passes — and
    // Arrays.deepToString is not injective, so it passed answers of the wrong shape.
    static void check(int index, Object actual, Object expected) {
        boolean ok = java.util.Objects.deepEquals(actual, expected);
        System.out.println("example " + index + (ok ? "  PASS" : "  FAIL — expected "
            + stringify(expected) + ", got " + stringify(actual)));
        if (!ok) failures++;
    }

    static Object stringify(Object value) {
        if (value instanceof int[] a) return java.util.Arrays.toString(a);
        if (value instanceof long[] a) return java.util.Arrays.toString(a);
        if (value instanceof double[] a) return java.util.Arrays.toString(a);
        if (value instanceof boolean[] a) return java.util.Arrays.toString(a);
        if (value instanceof Object[] a) return java.util.Arrays.deepToString(a);
        return value;
    }
}
