# Generated by programmers-tracker from the judge's own examples — do not edit; it is
# replaced after every run. Run it with:  python3 runner_test.py  (Solution.py beside it)
import Solution

failures = 0

def check(index, actual, expected):
    global failures
    ok = actual == expected
    print(f"example {index}  " + ("PASS" if ok else f"FAIL — expected {expected!r}, got {actual!r}"))
    if not ok:
        failures += 1

if __name__ == "__main__":
    check(1, Solution.solution(10, 5), 2)
    check(2, Solution.solution(7, 2), 3)
    print("ALL PASS" if failures == 0 else f"{failures} FAILED")
    if failures:
        raise SystemExit(1)
